### ISSUE TITLE
tw2.core>=2.1.2 breaks tw2.dynforms.GrowingGridLayout validation

### ISSUE THREAD

**Issue by moschlar** [toscawidgets/tw2.dynforms#3]
Since updating to `tw2.core>=2.1.2`, `GrowingGridLayout`'s fields don't get validated correctly anmore...

An example is at https://github.com/moschlar/SAUCE/blob/feature/simpleusers/sauce/widgets/judgement.py#L17

request.POST:

```
MultiDict([('judgement:assignment_id', u''), ('judgement:submission_id', u''), ('line', u''), ('comment', u''), ('line', u''), ('comment', u''), ('judgement:comment', u''), ('judgement:corrected_source', u''), ('judgement:grade', u'')])
```

After validation:

```
 {'comment': u"[u'', u'2', u'']", 'submission_id': 1, 'assignment_id': 1, 'grade': None, 'corrected_source': u'', 'annotations': []}
```

The problem seems to be that id and name are not the same anymore.
@ralphbean  confirmed the diversion between those in the rendered html.

**Comment by moschlar** [comment]
See also https://github.com/toscawidgets/tw2.core/issues/63

**Comment by ralphbean** [comment]
I almost lost the file I used to identify the issue.  Linking here for posterity:

https://gist.github.com/4021898

**Comment by ralphbean** [comment]
Fixed in https://github.com/toscawidgets/tw2.core/commit/df2920d83de2366993334f581744fede2877600b
